apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eureka-gateway  # Nome do Deployment que será escalado
  minReplicas: 1  # Número mínimo de réplicas
  maxReplicas: 4  # Número máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu  # Métrica de CPU
        target:
          type: Utilization
          averageUtilization: 80  # Se o uso de CPU for maior que 50%, o Kubernetes irá escalar
